# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.SmallIntegerField(default=3, verbose_name='阈值触发的次数')),
                ('alarm_type', models.CharField(choices=[('list', 'List'), ('sms', 'Sms'), ('email', 'Email')], default='list', max_length=32, verbose_name='告警方式')),
                ('is_solut', models.BooleanField(default=False, verbose_name='是否解决')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='告警开始时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='告警解决时间')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True, verbose_name='主机名')),
                ('ipaddress', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('macaddress', models.CharField(max_length=32, unique=True, verbose_name='MAC地址')),
                ('os_type', models.CharField(max_length=32, verbose_name='操作系统类型')),
                ('os_version', models.CharField(max_length=64, verbose_name='操作系统版本')),
                ('is_normal', models.BooleanField(default=True, verbose_name='是否正常')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='主机组名')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='指标名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模版名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(blank=True, choices=[('>', '>'), ('=', '='), ('<', '<'), ('!=', '!=')], default='>', max_length=16, verbose_name='语法')),
                ('value', models.CharField(max_length=16, verbose_name='阈值')),
                ('time', models.SmallIntegerField(default=0, verbose_name='触发次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '触发器',
                'verbose_name_plural': '触发器',
            },
        ),
        migrations.CreateModel(
            name='TriggerCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.SmallIntegerField(default=3, verbose_name='触发报警事件的次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '告警触发条件',
                'verbose_name_plural': '告警触发条件',
            },
        ),
    ]
