# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180601_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': '指标', 'verbose_name_plural': '指标'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': '模版', 'verbose_name_plural': '模版'},
        ),
        migrations.AlterField(
            model_name='host',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='macaddress',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本'),
        ),
    ]
